name: Publish

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: actions/npm@master
      with:
        args: ci
    - name: Test
      uses: actions/npm@master
      with:
        args: test
    - name: Automated releases for npm packages.
      uses: mikeal/merge-release@v4.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      if: github.ref == 'master'
